language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp-dev libgmp10

  # Install latest release of qsopt-ex library
  - wget https://github.com/jonls/qsopt-ex/releases/download/v2.5.10.3/qsopt-ex2_2.5.10.3-1_amd64.deb
  - sudo dpkg -i qsopt-ex2_2.5.10.3-1_amd64.deb
  - wget https://github.com/jonls/qsopt-ex/releases/download/v2.5.10.3/qsopt-ex-dev_2.5.10.3-1_amd64.deb
  - sudo dpkg -i qsopt-ex-dev_2.5.10.3-1_amd64.deb

  # Install Cython
  - pip install cython
  - pip install six

install: pip install .
script: ./test_qsoptex.py
