sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/qsopt_ex-2.5.10.3
addons:
  apt:
    packages:
      - libgmp-dev
      - libgmp10
install:
  # Install QSopt_ex library
  - if [ ! -f "$HOME/qsopt_ex-2.5.10.3/bin/esolver" ]; then
      ( mkdir src && cd src/;
        curl -LO https://github.com/jonls/qsopt-ex/releases/download/v2.5.10.3/qsopt_ex-2.5.10.3.tar.xz;
        tar -xvaf qsopt_ex-2.5.10.3.tar.xz;
        cd qsopt_ex-2.5.10.3/;
        ./configure --prefix="$HOME/qsopt_ex-2.5.10.3" && make install );
    fi
  - export CPATH="$HOME/qsopt_ex-2.5.10.3/include:$CPATH"
  - export LIBRARY_PATH="$HOME/qsopt_ex-2.5.10.3/lib:$LIBRARY_PATH"
  - export LD_LIBRARY_PATH="$HOME/qsopt_ex-2.5.10.3/lib:$LD_LIBRARY_PATH"

  # Install tox
  - pip install tox
script: tox -v
env:
  - TOXENV=py27
  - TOXENV=py34
